<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gsn" nsURI="http://acwg.org/3.0/gsn" nsPrefix="gsn_">
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="argumentation.ecore#//ArgumentPackage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContractModule" eSuperTypes="argumentation.ecore#//ArgumentPackageBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceNode" eSuperTypes="argumentation.ecore#//ArgumentAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="choice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="argumentation.ecore#//ArgumentAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refersToExternalMaterial"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="argumentation.ecore#//ArgumentReasoning">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="undeveloped" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="argumentation.ecore#//Claim">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="undeveloped" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toBeSupportedByContract"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Justification" eSuperTypes="argumentation.ecore#//Claim"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="argumentation.ecore#//Claim"/>
  <eClassifiers xsi:type="ecore:EClass" name="AwayGoal" eSuperTypes="argumentation.ecore#//Claim"/>
  <eClassifiers xsi:type="ecore:EClass" name="AwaySolution" eSuperTypes="argumentation.ecore#//ArtifactReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AwayContext" eSuperTypes="argumentation.ecore#//ArgumentAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleReference" eSuperTypes="argumentation.ecore#//ArtifactReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContractModuleReference" eSuperTypes="argumentation.ecore#//ArtifactReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ContractModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="argumentation.ecore#//ArtifactReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedBy" eSuperTypes="argumentation.ecore#//AssertedInference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMany" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isChoice" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InContextOf" eSuperTypes="argumentation.ecore#//AssertedContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMany" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isChoice" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
