<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HSUV Physical Architecture">
  <eClassifiers xsi:type="ecore:EClass" name="Steering System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Body"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cooling System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fuel System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Electrical System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Air Suspension System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="planetary Gear" ordered="false"
        lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wheel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interior Components"/>
  <eClassifiers xsi:type="ecore:EClass" name="Air Conditioning System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Chassis"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="planetary Gear" ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transmission"/>
  <eClassifiers xsi:type="ecore:EClass" name="Electric Motor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="planetary Gear" ordered="false"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braking System"/>
  <eClassifiers xsi:type="ecore:EClass" name="Battery System"/>
  <eClassifiers xsi:type="ecore:EClass" name="HSUV">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ICE" ordered="false" lowerBound="1"
        eType="#//ICE" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuel System" ordered="false"
        lowerBound="1" eType="#//Fuel%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="battery" ordered="false"
        lowerBound="1" eType="#//Electric%20Motor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="battery System" ordered="false"
        lowerBound="1" eType="#//Battery%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chassis" ordered="false"
        lowerBound="1" eType="#//Chassis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transmission System" ordered="false"
        lowerBound="1" eType="#//Transmission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suspension System" ordered="false"
        lowerBound="1" eType="#//Air%20Suspension%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheels" ordered="false"
        lowerBound="1" eType="#//Wheel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1"
        eType="#//Body" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braking System" ordered="false"
        lowerBound="1" eType="#//Braking%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steering System" ordered="false"
        lowerBound="1" eType="#//Steering%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electrical System" ordered="false"
        lowerBound="1" eType="#//Electrical%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cooling System" ordered="false"
        lowerBound="1" eType="#//Cooling%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="air Conditioning System"
        ordered="false" lowerBound="1" eType="#//Air%20Conditioning%20System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interior Components" ordered="false"
        lowerBound="1" eType="#//Interior%20Components" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
